# Generated by Django 4.2.7 on 2023-11-10 04:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenOrphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField()),
                ('needs', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='orphanage_imgs/')),
                ('visit', models.PositiveIntegerField(blank=True, default=0)),
                ('needs_clothes', models.IntegerField(blank=True, default=0)),
                ('needs_hygiene_supplies', models.IntegerField(blank=True, default=0)),
                ('needs_food', models.IntegerField(blank=True, default=0)),
                ('needs_money', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, choices=[('User', 'User'), ('Chief', 'Chief')], max_length=40)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('children_orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_visits', to='user.childrenorphanage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('children_orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childrenorphanage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('donated_item', models.CharField(blank=True, choices=[('clothes', 'Clothes'), ('hygiene', 'Hygiene Supplies'), ('food', 'Food'), ('money', 'Money')], max_length=20)),
                ('children_orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childrenorphanage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
